#!/bin/csh 
foreach w (0 1 2)
	setenv P part-$w
	if(! $w) setenv P all
	./puzzlebox --walls=2 --core-height=15 --core-diameter=10 --outer-sides=3 --nubs=1 --helix=1 --wall=$w --outer-initial=K > /tmp/small-test-$P.scad
	time openscad -o /tmp/small-test-$P.stl /tmp/small-test-$P.scad&
end
foreach w (0 1 2)
	setenv P part-$w
	if(! $w) setenv P all
	./puzzlebox --walls=2 --core-height=20 --core-diameter=10 --outer-sides=5 --wall=$w --outer-initial=K --inside > /tmp/small-test-inside-$P.scad
	time openscad -o /tmp/small-test-inside-$P.stl /tmp/small-test-inside-$P.scad&
end
foreach w (0 1 2)
	setenv P part-$w
	if(! $w) setenv P all
	./puzzlebox --walls=2 --core-height=85 --core-gap=20 --core-diameter=10 --outer-sides=4 --wall=$w --outer-initial='£' > /tmp/lottery-ticket-holder-$P.scad
	time openscad -o /tmp/lottery-ticket-holder-$P.stl /tmp/lottery-ticket-holder-$P.scad&
end
foreach s (20 50 75)
foreach w (0 1 2 3 4)
	setenv P part-$w
	if(! $w) setenv P all
	./puzzlebox --walls=4 --core-height=${s} --wall=$w > /tmp/box-${s}mm-$P.scad
	time openscad -o /tmp/box-${s}mm-$P.stl /tmp/box-${s}mm-$P.scad&
end
foreach w (0 1 2 3 4)
	setenv P part-$w
	if(! $w) setenv P all
	./puzzlebox --walls=4 --core-height=${s} --inside --wall=$w > /tmp/box-inside-${s}mm-$P.scad
	time openscad -o /tmp/box-inside-${s}mm-$P.stl /tmp/box-inside-${s}mm-$P.scad&
end
end
